#!/usr/bin/env bash
# Build a double-clickable LocalFlow.app (menu bar app, no Dock icon, no terminal).
#   bash scripts/make_mac_app.sh            # -> ~/Applications/LocalFlow.app
#   bash scripts/make_mac_app.sh /Applications/LocalFlow.app
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"
PY="$ROOT/.venv/bin/python"
if [[ ! -x "$PY" ]]; then
  echo "No .venv found. Run: bash scripts/setup.sh" >&2
  exit 1
fi
if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This script builds a macOS .app bundle; run it on a Mac." >&2
  exit 1
fi

# Finder may launch a script-based bundle under Rosetta (x86_64) even on an
# Apple Silicon Mac, and then the arm64 wheels in the venv cannot load. Detect
# the architecture the venv actually runs as and pin the launcher to it.
ARCH="$("$PY" -c 'import platform; print(platform.machine())')"
echo "Virtualenv architecture: $ARCH"

APP="${1:-$HOME/Applications/LocalFlow.app}"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/MacOS/LocalFlow" <<LAUNCHER
#!/bin/bash
# Generated by scripts/make_mac_app.sh. Runs LocalFlow from its virtualenv.
mkdir -p "\$HOME/.localflow"
echo "=== \$(date) launching LocalFlow.app with $PY" >> "\$HOME/.localflow/launch.log"
cd "$ROOT"
exec /usr/bin/arch -$ARCH "$PY" -m localflow run >> "\$HOME/.localflow/launch.log" 2>&1
LAUNCHER
chmod +x "$APP/Contents/MacOS/LocalFlow"

if [[ "$ARCH" == "arm64" ]]; then
  ARCH_KEYS='  <key>LSArchitecturePriority</key><array><string>arm64</string></array>
  <key>LSRequiresNativeExecution</key><true/>'
else
  ARCH_KEYS='  <key>LSArchitecturePriority</key><array><string>x86_64</string></array>'
fi

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>LocalFlow</string>
  <key>CFBundleDisplayName</key><string>LocalFlow</string>
  <key>CFBundleIdentifier</key><string>com.localflow.app</string>
  <key>CFBundleVersion</key><string>0.1.0</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>LocalFlow</string>
  <key>CFBundleIconFile</key><string>LocalFlow</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>LSUIElement</key><true/>
  <key>NSHighResolutionCapable</key><true/>
$ARCH_KEYS
  <key>NSMicrophoneUsageDescription</key>
  <string>LocalFlow listens to your voice and transcribes it on this Mac. Audio never leaves the computer.</string>
</dict>
</plist>
PLIST

# Icon: render the tray glyph at every size macOS wants, then pack it.
ICONSET="$(mktemp -d)/LocalFlow.iconset"
mkdir -p "$ICONSET"
"$PY" - "$ICONSET" <<'PYICON'
import sys
from localflow.tray import make_icon
out = sys.argv[1]
for size in (16, 32, 64, 128, 256, 512):
    make_icon("idle", size).save(f"{out}/icon_{size}x{size}.png")
    make_icon("idle", size * 2).save(f"{out}/icon_{size}x{size}@2x.png")
PYICON
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/LocalFlow.icns"

# Ad-hoc signature so macOS keeps the permissions you grant tied to this bundle.
codesign --force --deep --sign - "$APP" >/dev/null 2>&1 || true

echo "Built $APP"
echo
echo "Next:"
echo "  1. Open it (double-click, or Spotlight: LocalFlow). Nothing appears in the Dock;"
echo "     look for the mic in the menu bar and the floating widget at the right edge."
echo "  2. macOS will ask for Microphone and Accessibility. Approve both, then add"
echo "     LocalFlow under System Settings > Privacy & Security > Input Monitoring too."
echo "     Quit (menu bar icon > Quit LocalFlow) and open it again after granting."
echo "  3. Start at login: System Settings > General > Login Items > + > LocalFlow."
echo
echo "Logs: ~/.localflow/localflow.log and ~/.localflow/launch.log"
